import { library } from '@fortawesome/fontawesome-svg-core';
import {
    faArrowsRotate,
    faBan,
    faCheck,
    faChevronRight,
    faCircleInfo,
    faCloudDownloadAlt,
    faEye,
    faFileExcel,
    faFilter,
    faGears,
    faPen,
    faPlus,
    faRotateLeft,
    faSearch,
    faSort,
    faSortDown,
    faSortUp,
    faTable,
    faTrashAlt,
    faXmark,
} from '@fortawesome/free-solid-svg-icons';

library.add(
    faArrowsRotate,
    faBan,
    faCheck,
    faChevronRight,
    faCircleInfo,
    faCloudDownloadAlt,
    faEye,
    faFileExcel,
    faFilter,
    faGears,
    faPen,
    faPlus,
    faRotateLeft,
    faSearch,
    faSort,
    faSortDown,
    faSortUp,
    faTable,
    faTrashAlt,
    faXmark,
);
